name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [16-jdk]
    runs-on: ubuntu-latest
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew check build --stacktrace --parallel --warning-mode=fail
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
